-- AlterTable
ALTER TABLE `order` ADD COLUMN `advancePaymentConfirmed` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `advancePaymentConfirmedAt` DATETIME(3) NULL,
    ADD COLUMN `advancePaymentMethod` ENUM('CASH', 'TRANSFER', 'POINT_OF_SALE', 'MOBILE_PAYMENT', 'MIXED', 'BINANCE') NULL,
    ADD COLUMN `advanceReceiptUrl` VARCHAR(191) NULL,
    ADD COLUMN `deliveryAmount` DECIMAL(10, 2) NULL,
    ADD COLUMN `revisionAmount` DECIMAL(10, 2) NULL,
    MODIFY `status` ENUM('PENDING_PAYMENT', 'RECEIVED', 'DIAGNOSING', 'WAITING_APPROVAL', 'APPROVED', 'REPAIRING', 'WAITING_PART', 'READY', 'DELIVERED', 'CANCELLED') NOT NULL DEFAULT 'RECEIVED';

-- AlterTable
ALTER TABLE `orderstatushistory` MODIFY `status` ENUM('PENDING_PAYMENT', 'RECEIVED', 'DIAGNOSING', 'WAITING_APPROVAL', 'APPROVED', 'REPAIRING', 'WAITING_PART', 'READY', 'DELIVERED', 'CANCELLED') NOT NULL;
