-- WAITING_PART deja de existir: no tenía flujo propio. Las filas que lo usen
-- pasan a REPAIRING antes de achicar el enum.
UPDATE `order` SET `status` = 'REPAIRING' WHERE `status` = 'WAITING_PART';
UPDATE `orderstatushistory` SET `status` = 'REPAIRING' WHERE `status` = 'WAITING_PART';

-- AlterTable
ALTER TABLE `order` MODIFY `status` ENUM('PENDING_PAYMENT', 'RECEIVED', 'ON_THE_WAY', 'DIAGNOSING', 'WAITING_APPROVAL', 'APPROVED', 'REPAIRING', 'WAITING_EXTRA_PAYMENT', 'READY', 'PAID_PENDING_DELIVERY', 'REJECTED_PENDING_PICKUP', 'DELIVERED', 'CANCELLED') NOT NULL DEFAULT 'RECEIVED';

-- AlterTable
ALTER TABLE `orderstatushistory` MODIFY `status` ENUM('PENDING_PAYMENT', 'RECEIVED', 'ON_THE_WAY', 'DIAGNOSING', 'WAITING_APPROVAL', 'APPROVED', 'REPAIRING', 'WAITING_EXTRA_PAYMENT', 'READY', 'PAID_PENDING_DELIVERY', 'REJECTED_PENDING_PICKUP', 'DELIVERED', 'CANCELLED') NOT NULL;

-- AlterTable
ALTER TABLE `inventorymovement` ADD COLUMN `awaitingClientPayment` BOOLEAN NOT NULL DEFAULT false;
