-- AlterTable
ALTER TABLE `order` ADD COLUMN `budgetRejectionReason` TEXT NULL,
    MODIFY `status` ENUM('PENDING_PAYMENT', 'RECEIVED', 'DIAGNOSING', 'WAITING_APPROVAL', 'APPROVED', 'REPAIRING', 'WAITING_PART', 'READY', 'PAID_PENDING_DELIVERY', 'REJECTED_PENDING_PICKUP', 'DELIVERED', 'CANCELLED') NOT NULL DEFAULT 'RECEIVED';

-- AlterTable
ALTER TABLE `orderstatushistory` MODIFY `status` ENUM('PENDING_PAYMENT', 'RECEIVED', 'DIAGNOSING', 'WAITING_APPROVAL', 'APPROVED', 'REPAIRING', 'WAITING_PART', 'READY', 'PAID_PENDING_DELIVERY', 'REJECTED_PENDING_PICKUP', 'DELIVERED', 'CANCELLED') NOT NULL;
