-- AlterTable
ALTER TABLE `inventorymovement` MODIFY `channel` ENUM('MOSTRADOR', 'SERVICIO_TECNICO', 'AJUSTE_MANUAL', 'MERMA') NOT NULL DEFAULT 'AJUSTE_MANUAL';

-- AlterTable
ALTER TABLE `inventorymovement`
  ADD COLUMN `supplierName` VARCHAR(191) NULL,
  ADD COLUMN `destination` ENUM('TIENDA', 'DOMICILIO_CLIENTE', 'TALLER', 'OTRO') NULL,
  ADD COLUMN `lossReason` ENUM('DEFECTUOSO', 'DANIO_INSTALACION', 'PERDIDA', 'GARANTIA', 'OTRO') NULL;
